import type { Asset } from '../market-types.js'

export const BINANCE_SPOT_ASSETS: Asset[] = [
  {
    id: 'btc-usdt-binance',
    symbol: 'BTC/USDT',
    label: 'Bitcoin / USDT',
    type: 'Crypto',
    category: 'Cripto',
    source: 'BINANCE',
    marketType: 'CRYPTO',
    executionVenue: 'BINANCE_SPOT',
    marketSymbol: 'BTCUSDT',
    payout: 95,
    payout5min: 95,
    flag1: '₿',
    flag2: 'USDT',
    code1: 'crypto:btc',
    code2: 'us',
    price: 0,
    change24h: 0,
  },
  {
    id: 'eth-usdt-binance',
    symbol: 'ETH/USDT',
    label: 'Ethereum / USDT',
    type: 'Crypto',
    category: 'Cripto',
    source: 'BINANCE',
    marketType: 'CRYPTO',
    executionVenue: 'BINANCE_SPOT',
    marketSymbol: 'ETHUSDT',
    payout: 95,
    payout5min: 95,
    flag1: 'Ξ',
    flag2: 'USDT',
    code1: 'crypto:eth',
    code2: 'us',
    price: 0,
    change24h: 0,
  },
  {
    id: 'xrp-usdt-binance',
    symbol: 'XRP/USDT',
    label: 'Ripple / USDT',
    type: 'Crypto',
    category: 'Cripto',
    source: 'BINANCE',
    marketType: 'CRYPTO',
    executionVenue: 'BINANCE_SPOT',
    marketSymbol: 'XRPUSDT',
    payout: 95,
    payout5min: 95,
    flag1: '◉',
    flag2: 'USDT',
    code1: 'crypto:xrp',
    code2: 'us',
    price: 0,
    change24h: 0,
  },
  {
    id: 'sol-usdt-binance',
    symbol: 'SOL/USDT',
    label: 'Solana / USDT',
    type: 'Crypto',
    category: 'Cripto',
    source: 'BINANCE',
    marketType: 'CRYPTO',
    executionVenue: 'BINANCE_SPOT',
    marketSymbol: 'SOLUSDT',
    payout: 95,
    payout5min: 95,
    flag1: '◎',
    flag2: 'USDT',
    code1: 'crypto:sol',
    code2: 'us',
    price: 0,
    change24h: 0,
  },
  {
    id: 'bnb-usdt-binance',
    symbol: 'BNB/USDT',
    label: 'BNB / USDT',
    type: 'Crypto',
    category: 'Cripto',
    source: 'BINANCE',
    marketType: 'CRYPTO',
    executionVenue: 'BINANCE_SPOT',
    marketSymbol: 'BNBUSDT',
    payout: 95,
    payout5min: 95,
    flag1: '🪙',
    flag2: 'USDT',
    code1: 'crypto:bnb',
    code2: 'us',
    price: 0,
    change24h: 0,
  },
]

export const OTC_DEFAULT_CONFIG = {
  spread: 0.0002,
  liquidity: 1,
  speed: 200,
  initialPrice: 1,
  volatility: 0.0008,
  trend: 0,
  trendStrength: 0.3,
  enabled: true,
}
