// Forex module — shared types. Independent from OTC/Binance, but uses the
// same field naming conventions so a future unification (a `MarketProvider`
// covering all 3) would be a rename rather than a redesign.

/** Canonical timeframe identifiers (seconds). Matches the OTC convention. */
export const FOREX_TIMEFRAMES = [60, 300, 900, 3600] as const   // 1m, 5m, 15m, 1h
export type ForexTimeframe = typeof FOREX_TIMEFRAMES[number]

export function isForexTimeframe(n: number): n is ForexTimeframe {
  return (FOREX_TIMEFRAMES as readonly number[]).includes(n)
}

/** Asset config loaded once at boot, refreshed by admin reload. */
export interface ForexAssetConfig {
  id:              string         // 'eur-usd'
  symbol:          string         // 'EURUSD'  (cTrader convention, no slash)
  name:            string
  digits:          number         // price decimals
  pipSize:         number         // 0.0001 for EURUSD, 0.01 for USDJPY
  enabled:         boolean
  ctraderSymbolId: number | null  // resolved at boot via GetSymbolsListReq
  displayOrder:    number
}

/** Single normalized tick from any provider. Provider-specific extras
 *  (e.g., raw symbolId, sequence number) stripped before this point. */
export interface ForexTick {
  assetId:    string
  bid:        number
  ask:        number
  // Midpoint used for candle aggregation (some providers send only one side).
  mid:        number
  // Epoch ms when the tick was generated by the provider, NOT when we received.
  timestamp:  number
}

/** OHLC bar — same shape as the OTC candle so the frontend chart code can
 *  stay structurally identical across providers. */
export interface ForexCandle {
  assetId:     string
  timeframe:   ForexTimeframe
  openTime:    Date
  open:        number
  high:        number
  low:         number
  close:       number
  tickCount:   number
  // null while the candle is still aggregating, set once rolled over.
  finalizedAt: Date | null
}

/** Snapshot row written every 5s + on shutdown. Lets boot recovery resume
 *  the last known bid/ask without waiting for the provider to push a tick. */
export interface ForexSnapshot {
  assetId:         string
  ctraderSymbolId: number | null
  lastBid:         number | null
  lastAsk:         number | null
  lastTickAt:      Date | null
  updatedAt:       Date
}
